In [42]:
#Q3. Singular Value Decomposition (SVD):
#Perform Singular Value Decomposition on the matrix A obtained in Question 2.
# Separate and print matrices U, Σ, and 𝑉் . Verify that A equals the product of U, Σ, and 𝑉் . 
#Additionally, find the rank 2 and rank 3 approximations of matrix A

In [43]:
import numpy as np
import sympy as sp


In [44]:
# Define the matrix A

np.random.seed(22)
A = np.random.randint(0, 10, size=(5, 5))
print("Matrix A:")
print(A)

Matrix A:
[[5 4 0 4 6]
 [6 4 8 4 2]
 [8 7 2 9 8]
 [8 5 4 2 2]
 [1 6 9 3 3]]


In [45]:
# Perform Singular Value Decomposition
U, Sigma, Vt = np.linalg.svd(A)

In [46]:
# Print matrices U, Sigma, and Vt
print("Matrix U:")
print(U)
print("\nMatrix Sigma:")
print(np.diag(Sigma))
print("\nMatrix Vt (transpose of V):")
print(Vt)


Matrix U:
[[-0.34966012  0.41846152 -0.11715402  0.39622406 -0.72932105]
 [-0.43353269 -0.41989712  0.28603192 -0.61798002 -0.41475566]
 [-0.62245303  0.49217946 -0.25866209 -0.31889741  0.44912133]
 [-0.39627638 -0.0739169   0.72897936  0.47278946  0.28733349]
 [-0.38118822 -0.63314456 -0.55330253  0.36862144  0.1086188 ]]

Matrix Sigma:
[[24.70467411  0.          0.          0.          0.        ]
 [ 0.          9.70171042  0.          0.          0.        ]
 [ 0.          0.          5.3650222   0.          0.        ]
 [ 0.          0.          0.          2.36583297  0.        ]
 [ 0.          0.          0.          0.          1.08409568]]

Matrix Vt (transpose of V):
[[-0.52137989 -0.47596069 -0.39381079 -0.43194117 -0.3999554 ]
 [ 0.23561627 -0.07513501 -0.86260941  0.24496765  0.36706343]
 [ 0.80887963 -0.15098564 -0.05458954 -0.34564554 -0.44773455]
 [-0.05368171  0.61558456 -0.1576122  -0.72095423  0.27121453]
 [-0.12441868  0.60504144 -0.27017855  0.33789323 -0.65671651]

In [47]:

#U
U=sp.Matrix(np.round(U,3))

In [48]:
U

Matrix([
[ -0.35,  0.418, -0.117,  0.396, -0.729],
[-0.434,  -0.42,  0.286, -0.618, -0.415],
[-0.622,  0.492, -0.259, -0.319,  0.449],
[-0.396, -0.074,  0.729,  0.473,  0.287],
[-0.381, -0.633, -0.553,  0.369,  0.109]])

In [49]:
#create a sigma matrix
Sigma=np.zeros((A.shape[0],A.shape[1]))

In [50]:
s

array([24.70467411,  9.70171042,  5.3650222 ,  2.36583297,  1.08409568])

In [51]:
Sigma=np.zeros((A.shape[0],A.shape[1]))
sp.Matrix(Sigma)

Matrix([
[0, 0, 0, 0, 0],
[0, 0, 0, 0, 0],
[0, 0, 0, 0, 0],
[0, 0, 0, 0, 0],
[0, 0, 0, 0, 0]])

In [52]:
Sigma[:A.shape[1],:A.shape[0]]=np.diag(s)
sp.Matrix(Sigma)

Matrix([
[24.7046741080415,                0,                0,               0,                0],
[               0, 9.70171041557809,                0,               0,                0],
[               0,                0, 5.36502219661434,               0,                0],
[               0,                0,                0, 2.3658329654151,                0],
[               0,                0,                0,               0, 1.08409567719716]])

In [53]:
Sigma[:A.shape[1],:A.shape[0]]=np.diag(s)

In [54]:
Sigma

array([[24.70467411,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  9.70171042,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  5.3650222 ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  2.36583297,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.08409568]])

In [55]:
#Vt
Vt=sp.Matrix(np.round(Vt,3))

In [56]:
Vt

Matrix([
[-0.521, -0.476, -0.394, -0.432,   -0.4],
[ 0.236, -0.075, -0.863,  0.245,  0.367],
[ 0.809, -0.151, -0.055, -0.346, -0.448],
[-0.054,  0.616, -0.158, -0.721,  0.271],
[-0.124,  0.605,  -0.27,  0.338, -0.657]])

In [57]:
U@Sigma@Vt

Matrix([
[ 5.00154314740466,   4.005410784321, 0.00691878744361615, 4.00347920935238, 6.00129057399282],
[ 6.00050593186344, 4.00466688335315,    8.00897292656129, 4.00471982134062,  2.0052593511754],
[ 7.98858836243356, 6.99578334046492,    1.99926017406373, 8.99713376852367, 7.99649228294613],
[ 7.99261082571178, 4.99756543747194,    3.99816740375612,  1.9954816620034, 1.99641156822002],
[0.992601639461377, 5.99817901380491,     9.0016975339466, 2.99864733637021, 2.99927593176761]])

In [58]:
#  find the rank 2 and rank 3 approximation of matrix A

In [59]:
k=1
Uk=U[:,:k]
Sigmak=Sigma[:k,:k]
Vtk=Vt[:k,:]
Ak=Uk@Sigmak@Vtk
sp.Matrix(Ak)

Matrix([
[4.50489732360137, 4.11579870639971, 3.40677455949892, 3.73534672513587, 3.45865437512581],
[ 5.5860726812657, 5.10359039593565, 4.22440045377867, 4.63182993916848,   4.288731425156],
[8.00584610080015, 7.31436227251606, 6.05432507430952, 6.63824475152718, 6.14652291808073],
[5.09696954327469, 4.65673225066939, 3.85452207303307, 4.22627800901088, 3.91322037871377],
[4.90390251512035, 4.48034087753797, 3.70851744905454, 4.06619172079077, 3.76499233406552]])

In [60]:
k=2
Uk=U[:,:k]
Sigmak=Sigma[:k,:k]
Vtk=Vt[:k,:]
Ak=Uk@Sigmak@Vtk
sp.Matrix(Ak)

Matrix([
[5.46195165267731, 3.81165008487134, -0.0929622455542223, 4.72889888879523, 4.94695496313798],
[ 4.6244391448736, 5.40919427402636,     7.7408824110091,  3.6335239374055,  2.7933097816988],
[9.13233110057375, 6.95636915818123,    1.93501763869672, 7.80768892502097, 7.89830255755917],
[4.92753887257703, 4.71057674347585,    4.47409270359272, 4.05038599917645,  3.6497413272475],
[3.45458339955797, 4.94092957951754,    9.00835811316612, 2.56160196099084, 1.51117828571216]])

In [61]:
k=3
Uk=U[:,:k]
Sigmak=Sigma[:k,:k]
Vtk=Vt[:k,:]
Ak=Uk@Sigmak@Vtk
sp.Matrix(Ak)

Matrix([
[4.95413620670118, 3.90643393201893, -0.058438327719009, 4.94608571735857, 5.22816796659572],
[5.86576579059304, 5.17750042544337,   7.65649061185635, 3.10262280091733,   2.105900217691],
[8.00819263469495, 7.16618981126862,   2.01144237988749, 8.28847002414836, 8.52081681307672],
[ 8.0916197282745, 4.12000046509474,   4.25898213861946, 2.69714499043563, 1.89756799801083],
[1.05439586430323, 5.38892502800143,   9.17153526327615, 3.58813457804663, 2.84033034479019]])